/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.22
 * Generated at: 2012-10-24 21:57:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=US-ASCII");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <title>Steve Polyak (Coralville, IA USA)</title>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("\n");
      out.write("    <!-- Le styles -->\n");
      out.write("    <link href=\"../assets/css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("    <style type=\"text/css\">\n");
      out.write("      body {\n");
      out.write("        padding-top: 60px;\n");
      out.write("        padding-bottom: 40px;\n");
      out.write("      }\n");
      out.write("      .sidebar-nav {\n");
      out.write("        padding: 9px 0;\n");
      out.write("      }\n");
      out.write("    </style>\n");
      out.write("    <link href=\"../assets/css/bootstrap-responsive.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("      <script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("    <!-- Le fav and touch icons -->\n");
      out.write("    <link rel=\"shortcut icon\" href=\"../assets/ico/favicon.ico\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"144x144\" href=\"../assets/ico/apple-touch-icon-144-precomposed.png\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"114x114\" href=\"../assets/ico/apple-touch-icon-114-precomposed.png\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" sizes=\"72x72\" href=\"../assets/ico/apple-touch-icon-72-precomposed.png\">\n");
      out.write("    <link rel=\"apple-touch-icon-precomposed\" href=\"../assets/ico/apple-touch-icon-57-precomposed.png\">\n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("  <body>\n");
      out.write("\n");
      out.write("    <div class=\"navbar navbar-inverse navbar-fixed-top\">\n");
      out.write("      <div class=\"navbar-inner\">\n");
      out.write("        <div class=\"container-fluid\">\n");
      out.write("          <a class=\"btn btn-navbar\" data-toggle=\"collapse\" data-target=\".nav-collapse\">\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("          </a>\n");
      out.write("          <a class=\"brand\" href=\"#\">Steve Polyak</a>\n");
      out.write("          <div class=\"nav-collapse collapse\">\n");
      out.write("            <p class=\"navbar-text pull-right\">\n");
      out.write("              Coralville, IA USA\n");
      out.write("            </p>\n");
      out.write("            <ul class=\"nav\">\n");
      out.write("              <li class=\"active\"><a href=\"#\">Home</a></li>\n");
      out.write("              <li><a href=\"#projects\">Projects</a></li>\n");
      out.write("              <li><a href=\"#about\">About</a></li>\n");
      out.write("              <li><a href=\"#contact\">Contact</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </div><!--/.nav-collapse -->\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("      <div class=\"row-fluid\">\n");
      out.write("        <div class=\"span3\">\n");
      out.write("          <div class=\"well sidebar-nav\">\n");
      out.write("            <ul class=\"nav nav-list\">\n");
      out.write("              <li class=\"nav-header\">Social</li>\n");
      out.write("              <li class=\"active\"><a href=\"http://www.stevepolyak.com\">Web</a></li>\n");
      out.write("              <li><a href=\"http://www.facebook.com/StephenPolyak\">Facebook</a></li>\n");
      out.write("              <li><a href=\"http://twitter.com/StevePolyak\">Twitter</a></li>\n");
      out.write("              <li><a href=\" http://plus.google.com/u/0/102481889382463415287/posts\">Google+</a></li>\n");
      out.write("              <li><a href=\"http://www.linkedin.com/in/stevepolyak\">LinkedIn</a></li>\n");
      out.write("              <li><a href=\"http://www.flickr.com/photos/spolyak\">Flickr</a></li>\n");
      out.write("              <li><a href=\"http://www.youtube.com/user/spolyak/videos\">Youtube (spolyak)</a></li>\n");
      out.write("              <li><a href=\"http://www.youtube.com/user/stevepolyak/videos\">Youtube (stevepolyak)</a></li>\n");
      out.write("              <li><a href=\"http://claimid.com/stevepolyak\">Claimid</a></li>\n");
      out.write("              <li class=\"nav-header\">Professional</li>\n");
      out.write("              <li><a href=\"http://www.dai.ed.ac.uk/papers/authors/stevep.html\">Dept. of AI Papers</a></li>\n");
      out.write("              <li><a href=\"http://scholar.google.com/scholar?q=polyak+planning&ie=UTF-8&oe=UTF-8&hl=en&btnG=Search\">Google Scholar</a></li>\n");
      out.write("              <li><a href=\"http://www.dai.ed.ac.uk/groups/ssp/publications.html\">Research Group</a>\n");
      out.write("              <li><a href=\"http://isbn.nu/9781580530507/price\">Book Chapter</a>\n");
      out.write("              <li><a href=\"http://www.mel.nist.gov/psl/\">NIST Process Spec Language</a>\n");
      out.write("            </ul>\n");
      out.write("          </div><!--/.well -->\n");
      out.write("        </div><!--/span-->\n");
      out.write("        <div class=\"span6\">\n");
      out.write("          <div class=\"hero-unit\">\n");
      out.write("            <div id=\"myCarousel\" class=\"carousel slide\">\n");
      out.write("  \t\t\t  <!-- Carousel items -->\n");
      out.write("  \t\t\t  <div class=\"carousel-inner\">\n");
      out.write("    \t\t\t<div class=\"active item\">\n");
      out.write("    \t\t\t  <img src=\"../assets/img/steve/c2.jpg\"/>\n");
      out.write("    \t\t\t  <div class=\"carousel-caption\">\n");
      out.write("                      <h4>Work</h4>\n");
      out.write("                      <p></p>\n");
      out.write("                    </div>\n");
      out.write("    \t\t\t</div>\n");
      out.write("    \t\t\t<div class=\"item\">\n");
      out.write("    \t\t\t  <img src=\"../assets/img/steve/c0.jpg\"/>\n");
      out.write("    \t\t\t  <div class=\"carousel-caption\">\n");
      out.write("                      <h4>Family</h4>\n");
      out.write("                      <p></p>\n");
      out.write("                    </div>\n");
      out.write("    \t\t\t</div>\n");
      out.write("     \t\t\t<div class=\"item\">\n");
      out.write("    \t\t\t  <img src=\"../assets/img/steve/c1.jpg\"/>\n");
      out.write("    \t\t\t  <div class=\"carousel-caption\">\n");
      out.write("                      <h4>Cycling</h4>\n");
      out.write("                      <p></p>\n");
      out.write("                    </div>\n");
      out.write("    \t\t\t</div>   \t\t\t\n");
      out.write("  \t\t\t  </div>\n");
      out.write("  \t\t\t  <!-- Carousel nav -->\n");
      out.write("  \t\t\t  <a class=\"carousel-control left\" href=\"#myCarousel\" data-slide=\"prev\">&lsaquo;</a>\n");
      out.write("  \t\t\t  <a class=\"carousel-control right\" href=\"#myCarousel\" data-slide=\"next\">&rsaquo;</a>\n");
      out.write("            </div>\n");
      out.write("            <p></p>\n");
      out.write("            <p><a class=\"btn btn-primary btn-large\">Learn more &raquo;</a></p>\n");
      out.write("          </div>\n");
      out.write("          \n");
      out.write("          <div class=\"row-fluid\">\n");
      out.write("            <div class=\"span4\">\n");
      out.write("              <h2>Work</h2>\n");
      out.write("              <p>Software developer at Pearson.  </p>\n");
      out.write("              <p><a class=\"btn\" href=\"#\">View details &raquo;</a></p>\n");
      out.write("            </div><!--/span-->\n");
      out.write("            <div class=\"span4\">\n");
      out.write("              <h2>Family</h2>\n");
      out.write("              <p>Married to Amy Sundermann, Children: Lucy and Joey.</p>\n");
      out.write("              <p><a class=\"btn\" href=\"#\">View details &raquo;</a></p>\n");
      out.write("            </div><!--/span-->\n");
      out.write("            <div class=\"span4\">\n");
      out.write("              <h2>Education</h2>\n");
      out.write("              <p>Ph.D. University of Edinburgh, M.Sc. DePaul, B.Sc. University of Iowa.</p>\n");
      out.write("              <p><a class=\"btn\" href=\"#\">View details &raquo;</a></p>\n");
      out.write("            </div><!--/span-->\n");
      out.write("          </div><!--/row-->\n");
      out.write("        </div><!--/span-->\n");
      out.write("        <div class=\"span3\">\n");
      out.write("        </div><!--/span-->\n");
      out.write("      </div><!--/row-->\n");
      out.write("\n");
      out.write("      <hr>\n");
      out.write("\n");
      out.write("      <footer>\n");
      out.write("        <p>stevepolyak.com</p>\n");
      out.write("      </footer>\n");
      out.write("\n");
      out.write("    </div><!--/.fluid-container-->\n");
      out.write("\n");
      out.write("    <!-- Le javascript\n");
      out.write("    ================================================== -->\n");
      out.write("    <!-- Placed at the end of the document so the pages load faster -->\n");
      out.write("    <script src=\"../assets/js/jquery-1.8.2.js\"></script>\n");
      out.write("    <script src=\"../assets/js/bootstrap-transition.js\"></script>\n");
      out.write("    <script src=\"../assets/js/bootstrap-alert.js\"></script>\n");
      out.write("    <script src=\"../assets/js/bootstrap-modal.js\"></script>\n");
      out.write("    <script src=\"../assets/js/bootstrap-dropdown.js\"></script>\n");
      out.write("    <script src=\"../assets/js/bootstrap-scrollspy.js\"></script>\n");
      out.write("    <script src=\"../assets/js/bootstrap-tab.js\"></script>\n");
      out.write("    <script src=\"../assets/js/bootstrap-tooltip.js\"></script>\n");
      out.write("    <script src=\"../assets/js/bootstrap-popover.js\"></script>\n");
      out.write("    <script src=\"../assets/js/bootstrap-button.js\"></script>\n");
      out.write("    <script src=\"../assets/js/bootstrap-collapse.js\"></script>\n");
      out.write("    <script src=\"../assets/js/bootstrap-carousel.js\"></script>\n");
      out.write("    <script src=\"../assets/js/bootstrap-typeahead.js\"></script>\n");
      out.write("\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
